### DATE_FOMAT(A, '날짜 어떻게 표시할지')
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE

### JOIN
FROM USED_GOODS_REPLY R
    LEFT JOIN USED_GOODS_BOARD B
    ON B.BOARD_ID = R.BOARD_ID

-- USED_GOODS_REPLY를 R로 취급 , USED_GOODS_BOARD를 B로 취급
-- B의 왼쪽에 R을 JOIN 한다. 
-- ON 뭐를 기준으로 JOIN할건지 

### 오름차순 -- 이중 오름 차순 
ORDER BY R.CREATED_DATE, B.TITLE;
