SELECT   FIRST_HALF.FLAVOR
FROM FIRST_HALF 
     LEFT JOIN ICECREAM_INFO
     ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
     
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC

-- 둘 다 정답 

SELECT F.FLAVOR
FROM FIRST_HALF F
    INNER JOIN
    (
        SELECT FLAVOR
        FROM ICECREAM_INFO
        WHERE INGREDIENT_TYPE = 'fruit_based'
    ) I
    ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000
ORDER BY F.TOTAL_ORDER DESC;
