WITH A AS (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID
HAVING PARENT_ID IS NOT NULL)

SELECT B.ID, IFNULL(A.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA AS B
     LEFT JOIN A
     ON B.ID = A.PARENT_ID
