WITH A AS (SELECT FISH_TYPE,MAX(LENGTH) 
FROM FISH_INFO 
GROUP BY FISH_TYPE)

SELECT AA.ID, FISH_NAME, LENGTH
FROM FISH_INFO AA
     LEFT JOIN FISH_NAME_INFO BB
     ON AA.FISH_TYPE = BB.FISH_TYPE
WHERE (AA.FISH_TYPE, LENGTH) IN (SELECT * FROM A)
ORDER BY AA.ID 


