WITH A AS (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
       MAX(SIZE_OF_COLONY) AS MAX
        
FROM ECOLI_DATA 
GROUP BY YEAR)

SELECT A.YEAR,A.MAX- AA.SIZE_OF_COLONY AS YEAR_DEV,AA.ID
FROM ECOLI_DATA AA
     LEFT JOIN A
     ON YEAR(AA.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV
