WITH A AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE )



SELECT DISTINCT CAR_ID,
        CASE 
        WHEN CAR_ID IN (SELECT * FROM A)   THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

ORDER BY CAR_ID DESC

-- group by  안쓰고는 위에처럼 풀었꼬.... group by를 쓰려면...
--DISTINCT 안쓰고 어차피 CAR_ID, AVAILABILITY 조합이 다 똑같으니까 마지막에 GROUP BY CAR_ID 써도됨.
-- 또, 서브 쿼리 안쓰고 걍 MAX 때려도 되긴함. 
SELECT CAR_ID,
MAX(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE)
THEN '대여중'
ELSE '대여 가능'
END) AS 'AVAILABILITY'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
