-- 
SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE --AS 뒤에는 R. 붙이지 않기 
FROM USED_GOODS_REPLY R 
    LEFT JOIN USED_GOODS_BOARD B -- R +B 순서대로 JOIN 하는 게 LEFT JOIN 
    ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE, B.TITLE; -- 이중 오름차순 

