-- 3세대의 대장균 ID 출력 

SELECT A.ID -- , A.PARENT_ID AS P, B.PARENT_ID AS PP, C.PARENT_ID AS PPP
FROM ECOLI_DATA A
     LEFT JOIN ECOLI_DATA B 
     ON A.PARENT_ID = B.ID
     LEFT JOIN ECOLI_DATA C
     ON B.PARENT_ID = C.ID
WHERE B.PARENT_ID IS NOT NULL AND C.PARENT_ID IS NULL 
ORDER BY A.ID
